let products = [
  {
    id: 86,
    category_id: 14,
    category_name: "Cemilan",
    sku: "MHZVTK",
    name: "Ciki ciki",
    description: "Ciki ciki yang super enak, hanya di toko klontong kami",
    weight: 500,
    width: 5,
    length: 5,
    height: 5,
    image: "https://cf.shopee.co.id/file/7cb930d1bd183a435f4fb3e5cc4a896b",
    harga: 30000
  },
  {
    id: 87,
    category_id: 14,
    category_name: "Cemilan",
    sku: "PLMNOQ",
    name: "Keripik Singkong Balado",
    description: "Keripik singkong pedas manis, bikin nagih!",
    weight: 250,
    width: 4,
    length: 6,
    height: 3,
    image: "https://example.com/keripik-singkong.jpg",
    harga: 15000
  },
  {
    id: 88,
    category_id: 15,
    category_name: "Minuman",
    sku: "QWERTY",
    name: "Es Teh Manis",
    description: "Segar dan nikmat, pelepas dahaga.",
    weight: 300,
    width: 7,
    length: 7,
    height: 10,
    image: "https://example.com/es-teh.jpg",
    harga: 8000
  },
  {
    id: 89,
    category_id: 16,
    category_name: "Kebutuhan Pokok",
    sku: "AZBYCX",
    name: "Beras Premium 5kg",
    description: "Beras pilihan kualitas terbaik untuk keluarga.",
    weight: 5000,
    width: 30,
    length: 20,
    height: 10,
    image: "https://example.com/beras-premium.jpg",
    harga: 65000
  },
  {
    id: 90,
    category_id: 14,
    category_name: "Cemilan",
    sku: "POIUYT",
    name: "Permen Aneka Rasa",
    description: "Berbagai rasa permen dalam satu kemasan.",
    weight: 100,
    width: 3,
    length: 8,
    height: 2,
    image: "https://example.com/permen-aneka-rasa.jpg",
    harga: 5000
  },
  {
    id: 91,
    category_id: 15,
    category_name: "Minuman",
    sku: "LKJHGF",
    name: "Kopi Hitam Bubuk",
    description: "Kopi bubuk asli, siap seduh.",
    weight: 200,
    width: 10,
    length: 12,
    height: 5,
    image: "https://example.com/kopi-hitam.jpg",
    harga: 25000
  },
  {
    id: 92,
    category_id: 17,
    category_name: "Peralatan Rumah Tangga",
    sku: "ZXCVBN",
    name: "Sabun Cuci Piring",
    description: "Efektif membersihkan noda minyak.",
    weight: 750,
    width: 6,
    length: 6,
    height: 20,
    image: "https://example.com/sabun-cuci.jpg",
    harga: 12000
  },
  {
    id: 93,
    category_id: 14,
    category_name: "Cemilan",
    sku: "MNBVCX",
    name: "Roti Coklat Keju",
    description: "Roti lembut dengan isian coklat dan keju melimpah.",
    weight: 150,
    width: 10,
    length: 8,
    height: 4,
    image: "https://example.com/roti-coklat-keju.jpg",
    harga: 10000
  },
  {
    id: 94,
    category_id: 15,
    category_name: "Minuman",
    sku: "ASDFGH",
    name: "Susu UHT Coklat",
    description: "Susu segar rasa coklat, cocok untuk sarapan.",
    weight: 1000,
    width: 7,
    length: 7,
    height: 25,
    image: "https://example.com/susu-uht.jpg",
    harga: 18000
  },
  {
    id: 95,
    category_id: 16,
    category_name: "Kebutuhan Pokok",
    sku: "TYUIOP",
    name: "Minyak Goreng 2L",
    description: "Minyak goreng berkualitas tinggi untuk memasak.",
    weight: 2000,
    width: 15,
    length: 10,
    height: 30,
    image: "https://example.com/minyak-goreng.jpg",
    harga: 35000
  }
];

export default products;